# Generated by Django 5.2.5 on 2025-10-24 05:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('general_start_point', models.CharField(max_length=255)),
                ('general_end_point', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Route',
                'verbose_name_plural': 'User Routes',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=255)),
                ('start_point_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_point_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_point_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_point_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_km', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_type', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='routes.userroute')),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'indexes': [models.Index(fields=['user_route', 'segment_number'], name='routes_segm_user_ro_3e3be3_idx')],
            },
        ),
    ]
