# Generated by Django 5.2.5 on 2026-07-10 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'segment', 'verbose_name_plural': 'segments'},
        ),
        migrations.AlterField(
            model_name='segment',
            name='distance_km',
            field=models.PositiveIntegerField(verbose_name='distance (km)'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes or seconds', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_point_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='end latitude'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_point_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='end longitude'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='segment name'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='segment number'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_point_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='start latitude'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_point_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='start longitude'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='transport_type',
            field=models.CharField(help_text='e.g. Train, Flight, Bus', max_length=50, verbose_name='transport type'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='user_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='routes.userroute', verbose_name='route'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('user_route', 'segment_number'), name='unique_route_segment_number'),
        ),
    ]
