# Generated by Django 5.2.5 on 2026-07-10 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_segment_options_alter_segment_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroute',
            options={'ordering': ['-created_at'], 'verbose_name': 'user route', 'verbose_name_plural': 'user routes'},
        ),
        migrations.AddField(
            model_name='userroute',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='userroute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='general_end_point',
            field=models.CharField(max_length=255, verbose_name='general end point'),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='general_start_point',
            field=models.CharField(max_length=255, verbose_name='general start point'),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='route name'),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
