# Generated by Django 5.2.5 on 2025-10-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_level',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sociallogin',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountLevel',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SocialLogin',
        ),
    ]
