name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - develop  # деплой при пуше в develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Упаковываем код в архив
    - name: Create archive
      run: |
        git archive -o deploy.zip HEAD

    # 3️⃣ Загружаем архив на PythonAnywhere
    - name: Upload to PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/files/path/home/${PA_USERNAME}/AllWays/deploy.zip" \
             -H "Authorization: Token ${PA_TOKEN}" \
             -F "file=@deploy.zip"

    # 4️⃣ Распаковываем архив, устанавливаем зависимости и перезагружаем веб-приложение
    - name: Unpack, install dependencies and reload
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/bash/" \
             -H "Authorization: Token ${PA_TOKEN}" \
             -d "command='rm -rf ~/AllWays/* && unzip -o ~/AllWays/deploy.zip -d ~/AllWays/ && python3 -m pip install --upgrade pip && pip install -r ~/AllWays/backend/requirements.txt && pa_reload ${PA_USERNAME}.pythonanywhere.com'"
