name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Настройка Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3️⃣ Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # 4️⃣ Деплой на PythonAnywhere через GitHub API
    - name: Push to PythonAnywhere repo
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        git remote add pa "https://${PA_USERNAME}:${PA_TOKEN}@github.com/${PA_USERNAME}/AllWays.git"
        git push pa develop -f

    # 5️⃣ Перезагрузка веб-приложения через API (без открытия консоли)
    - name: Reload webapp on PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/" \
             -H "Authorization: Token ${PA_TOKEN}"
