name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Archive project
      run: git archive -o deploy.zip HEAD

    - name: Upload deploy.zip to PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/files/path/home/${PA_USERNAME}/AllWays/deploy.zip" \
             -H "Authorization: Token ${PA_API_TOKEN}" \
             -F "file=@deploy.zip"

    - name: Unpack and reload webapp on PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/bash_commands/" \
             -H "Authorization: Token ${PA_API_TOKEN}" \
             -H "Content-Type: application/json" \
             -d '{
                   "commands": [
                     "unzip -o /home/'"${PA_USERNAME}"'/AllWays/deploy.zip -d /home/'"${PA_USERNAME}"'/AllWays",
                     "source /home/'"${PA_USERNAME}"'/.virtualenvs/AllWays/bin/activate",
                     "pip install -r /home/'"${PA_USERNAME}"'/AllWays/backend/requirements.txt"
                   ]
                 }'

        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/" \
             -H "Authorization: Token ${PA_API_TOKEN}"

    - name: Cleanup old deploy archive
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/bash_commands/" \
             -H "Authorization: Token ${PA_API_TOKEN}" \
             -H "Content-Type: application/json" \
             -d '{"commands":["rm -f /home/'"${PA_USERNAME}"'/AllWays/deploy.zip"]}'
